In [1]:
#q1
"""
the data type of list will be a list and of array will be nd.array"""
import numpy as np
l=[1,"sd",9,8.9]
print(type(list))
a=np.array([1,2,45,67])
print(a)
print(type(a))

<class 'type'>
[ 1  2 45 67]
<class 'numpy.ndarray'>


In [2]:
#q2
l=[1,23,6.7,"gaurisha"]
b=np.array([1,3,8.9,"gau"])
for i in l:
    print(type(i))
for j in b:
    print(type(j))

<class 'int'>
<class 'int'>
<class 'float'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [3]:
#q4
arr1=np.array([[12,23,67],[12,78,90]])
print(arr1)
print(arr1.size)
print(arr1.shape)


[[12 23 67]
 [12 78 90]]
6
(2, 3)


In [4]:
#q5
z=np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
#q6
m=np.eye(5)
print(m)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
